from item_types import Item, Game

EXTRAS: list[Item] = [
    Game(
        "Turbo Golf Racing",
        None,
        "https://store.steampowered.com/app/1324350/Turbo_Golf_Racing",
        False,
        ["steam", "windows"],
    ),
    Game(
        "Kingdom Two Crowns",
        None,
        "https://store.steampowered.com/app/701160/Kingdom_Two_Crowns",
        False,
        ["steam", "windows", "linux", "macos"],
    ),
    Game(
        "Field of Glory II",
        None,
        "https://store.steampowered.com/app/660160/Field_of_Glory_II",
        False,
        ["steam", "windows"],
    ),
    Game(
        "Steel Rats™",
        None,
        "https://store.steampowered.com/app/619700/Steel_Rats",
        False,
        ["steam", "windows", "linux", "macos"],
    ),
    Game(
        "Rescue Party: Live!",
        None,
        "https://store.steampowered.com/app/1662570/Rescue_Party_Live",
        False,
        ["steam", "windows"],
    ),
    Game(
        "Chivalry: Medieval Warfare",
        None,
        "https://store.steampowered.com/app/219640/Chivalry_Medieval_Warfare",
        False,
        ["steam", "windows", "linux", "macos"],
    ),
    Game(
        "Arcade Paradise - Arcade Paradise EP",
        None,
        "https://store.steampowered.com/app/1662570/Rescue_Party_Live",
        False,
        ["steam", "windows"],
    ),
    Game(
        "STONE",
        None,
        "https://store.steampowered.com/app/907770/STONE",
        False,
        ["steam", "windows", "macos"],
    ),
    Game(
        "White Day: A Labyrinth Named School",
        None,
        "https://store.steampowered.com/app/466130/White_Day_A_Labyrinth_Named_School",
        False,
        ["steam", "windows"],
    ),
    Game(
        "PlateUp!",
        None,
        "https://store.steampowered.com/app/1599600/PlateUp",
        False,
        ["steam", "windows"],
    ),
    Game(
        "Perfect",
        None,
        "https://store.steampowered.com/app/540740/Perfect",
        False,
        ["steam", "windows"],
    ),
    Game(
        "Warhammer 40,000: Gladius - Relics of War",
        None,
        "https://store.steampowered.com/app/489630/Warhammer_40000_Gladius__Relics_of_War",
        False,
        ["steam", "windows"],
    ),
]
