# These are known names that are not consistent
# Some entries in the JSON file use one name, while others use other :shrug:
FIXES = {
    "7 Grand Steps": "7 Grand Steps: What Ancients Begat",
    "Amnesia: The Dark Descent": "Amnesia: The Dark Descent + Amnesia: A Machine for Pigs",
    "Anomaly Warzone Earth: Mobile Campaign": "Anomaly Warzone Earth",
    "Assault Android Cactus": "Assault Android Cactus+",
    "Automate the Boring Stuff with Python": "Automate the Boring Stuff with Python: Practical Programming for Total Beginners",
    "Brutal Legend": "Brütal Legend",
    "Dusty Revenge: Co-op Edition": "Dusty Revenge: Co-Op Edition",
    "EarthNight Wallpapers": "EarthNight",
    "Framed Collection": "FRAMED Collection",
    "Frog Detective": "The Haunted Island, a Frog Detective Game",
    "FTL": "FTL: Faster than Light",
    "Guacamelee Super Turbo Championship Edition": "Guacamelee! Super Turbo Championship Edition",
    "Hot Tin Roof": "Hot Tin Roof: The Cat That Wore A Fedora Deluxe",
    "Ironclad Tactics Deluxe": "Ironclad Tactics",
    "Loot Rascals Soundtrack": "Loot Rascals",
    "Overgrowth Steam key": "Overgrowth",
    "Q.U.B.E: Director's Cut": "Q.U.B.E.: Director's Cut",
    "Retro Game Crunch (7 game package)": "Retro Game Crunch",
    "Rocket Birds: Hardboiled Chicken": "Rocketbirds: Hardboiled Chicken",
    "Secrets of Raetikon": "Secrets of Rætikon",
    "Tetrobot and Co. Steam": "Tetrobot and Co.",
    "The Inner World Soundtrack": "The Inner World",
}
