# These are known names that are not consistent
# Some entries in the JSON file use one name, while others use other :shrug:
FIXES: dict[str, str] = {
    "7 Grand Steps": "7 Grand Steps: What Ancients Begat",
    "A Double Fine Adventure Full": "Double Fine Adventure",
    "A Virus Named Tom": "A Virus Named TOM",
    "AI War: Fleet Command+3 DLCs": "AI War: Fleet Command",
    "Amnesia: The Dark Descent": "Amnesia: The Dark Descent + Amnesia: A Machine for Pigs",
    "Anomaly Warzone Earth: Mobile Campaign": "Anomaly Warzone Earth",
    "Assault Android Cactus": "Assault Android Cactus+",
    "Automate the Boring Stuff with Python": "Automate the Boring Stuff with Python: Practical Programming for Total Beginners",
    "Brutal Legend": "Brütal Legend",
    "Day of the Tentacle": "Day of the Tentacle Remastered",
    "Double Fine Adventure Documentary": "Double Fine Adventure",
    "Double Fine Adventure Ep.01": "Double Fine Adventure",
    "Double Fine Adventure Ep.02": "Double Fine Adventure",
    "Double Fine Adventure Ep.03": "Double Fine Adventure",
    "Double Fine Adventure Ep.04": "Double Fine Adventure",
    "Double Fine Adventure Ep.05": "Double Fine Adventure",
    "Double Fine Adventure Ep.06": "Double Fine Adventure",
    "Double Fine Adventure Ep.07": "Double Fine Adventure",
    "Double Fine Adventure Ep.08": "Double Fine Adventure",
    "Double Fine Adventure Ep.09": "Double Fine Adventure",
    "Double Fine Adventure Ep.10": "Double Fine Adventure",
    "Double Fine Adventure Ep.11": "Double Fine Adventure",
    "Double Fine Adventure Ep.12": "Double Fine Adventure",
    "Double Fine Adventure Ep.13": "Double Fine Adventure",
    "Double Fine Adventure Ep.14": "Double Fine Adventure",
    "Double Fine Adventure Ep.15": "Double Fine Adventure",
    "Double Fine Adventure Ep.16": "Double Fine Adventure",
    "Double Fine Adventure Ep.17": "Double Fine Adventure",
    "Double Fine Adventure Ep.18": "Double Fine Adventure",
    "Double Fine Adventure Ep.19": "Double Fine Adventure",
    "Double Fine Adventure Ep.20": "Double Fine Adventure",
    "Dusty Revenge: Co-op Edition": "Dusty Revenge: Co-Op Edition",
    "EarthNight Wallpapers": "EarthNight",
    "Framed Collection": "FRAMED Collection",
    "Frog Detective": "The Haunted Island, a Frog Detective Game",
    "FTL": "FTL: Faster than Light",
    "Guacamelee Super Turbo Championship Edition": "Guacamelee! Super Turbo Championship Edition",
    "Hot Tin Roof": "Hot Tin Roof: The Cat That Wore A Fedora Deluxe",
    "Ironclad Tactics Deluxe": "Ironclad Tactics",
    "Loot Rascals Soundtrack": "Loot Rascals",
    "Overgrowth Steam key": "Overgrowth",
    "PDF-Suite": "PDF-Suite Standard",
    "Q.U.B.E: Director's Cut": "Q.U.B.E.: Director's Cut",
    "Retro Game Crunch (7 game package)": "Retro Game Crunch",
    "Rocket Birds: Hardboiled Chicken": "Rocketbirds: Hardboiled Chicken",
    "Secrets of Raetikon": "Secrets of Rætikon",
    "Tetrobot and Co. Steam": "Tetrobot and Co.",
    "The Inner World Soundtrack": "The Inner World",
}
